TypeFox/monaco-languageclient

- src/converter.ts
In #11, I realized that if my Diagnostic's `code` property was set to the `0` number, Monaco would refuse to render my code actions. This is because VSCode's IMarkerData expects its `code` property to be a `string`. [`as string`](https://github.com/TypeFox/monaco-languageclient/blob/8fad2e2bc7e34e687cd010680cef4fc99cead3a2/src/converter.ts#L518) is used in converter.ts to cast the Diagnostic's `code` to a `string` but this doesn't actually do anything in the transpiled JavaScript.
```JavaScript
ProtocolToMonacoConverter.prototype.asMarker = function (diagnostic) {
return {
code: diagnostic.code,
severity: this.asSeverity(diagnostic.severity),
message: diagnostic.message,
source: diagnostic.source,
startLineNumber: diagnostic.range.start.line + 1,
startColumn: …
```
> Convert Diagnostic's code to a string for VSCode's IMarkerData

- .travis.yml
- package.json
There should be a CI system for building this package that tests it with Node.js 8 and NPM 5 since it seems so fail (see issue https://github.com/TypeFox/monaco-languageclient/issues/8).
I like Travis so I created a .travis.yml (after merging this it would need to be enabled at https://travis-ci.org. This could also be used for an automated release process as a next step.
You can see how it looks like here: https://travis-ci.org/franzbecker/monaco-languageclient/
> Integrate with Travis in order to build with node 7 and 8

- example/package.json
Extracted ./node_modules/.bin/webpack into separate alias to avoid error:
> '.' is not recognized as an internal or external command' on Windows
> Removed ./node_modules/.bin/webpack from npm run scripts

- src/converter.ts
- src/diagnostic-collection.ts
- src/languages.ts
It's fine to `import X = monaco.X` for types, but not for objects such as `monaco.Uri` and `monaco.languages`. This PR inlines these references to allow monaco to be loaded lazily.
Fixes #16
> Allow for lazy loading of monaco

- example/src/client.ts
- example/src/json-server-launcher.ts
- example/src/json-server.ts
- src/commands.ts
- src/converter.ts
- src/index.ts
- src/services.ts
- src/workspace.ts
- tsconfig.json
- typings/monaco/index.d.ts
This implements a basic applyEdit operation (more advanced ones would accept the editor and preserve / manipulate the current selections), as well as registering commands against a given editor.
Fixes #11 
Fixes #12
> Provide support for commands

- package.json
- src/converter.ts
- src/languages.ts
I bumped the versions in the `package.json` file and also fixed a compilation error caused by the removal of the [CodeAction interface](https://github.com/Microsoft/monaco-editor/commit/e5c642781a30318de8f5406fdd427f8a4acc587a).
> Update Monaco dependency to 0.10.0

- src/languages.ts
In browser test shown that monaco still call the resolver in all cases,
so we can't use undefined here.
Thanks for the library :)
> When the language server doesn't provide a resolve option, return the original codelens

- src/languages.ts
- typings/glob-to-regexp/index.d.ts
Signed-off-by: Alex Tugarev <alex.tugarev@typefox.io>
> fix glob-to-regexp d.ts

- src/converter.ts
- src/languages.ts
I've updated the code to add support for `textDocument/documentLink` and `documentLink/resolve` so that Monaco will show links provided by the language server. These links will be clickable via Ctrl+Click (maybe some other key or gesture on a Mac, I don't know, sorry).
Because of the discrepancy between the LSP's `DocumentLink` and Monaco's `ILink` (see Microsoft/monaco-editor#719), I had to do some casting to get around a compiler error.
> Add support for textDocument/documentLink and documentLink/resolve

- src/workspace.ts
In #21 support for the `workspace/applyEdit` request was added so the client should state this fact in its `WorkspaceClientCapabilites`.
My language server will only provide code actions if the client supports `workspace/applyEdit` requests so I need this to be enabled correctly so that my language server will work with this editor.
> State that the WorkspaceClientCapabilites's applyEdit capability is enabled

- src/workspace.ts
Support for `workspace/applyEdit` was added in #21 but the capabilities of the client was not updated to include `workspaceEdit: { documentChanges: true }`. This pull request adds this to the capabilities so that servers will know that this client supports this feature.
In an [earlier comment](https://github.com/TypeFox/monaco-languageclient/pull/55#discussion_r167476391) I had stated that our support for `documentChanges` was incomplete because no version checking was made. However, I was wrong because the versions were being checked by `vscode-base-languageclient`.
https://github.com/TypeFox/vscode-languageserver-node/blob/e0c1f194dabede0409f0d8f4e4e2eeccc65e1535/client/src/base.ts#L1502-L1512
Hence, the versions of the `documentChanges` have actually already been verified by the time …
> Update WorkspaceClientCapabilities to state that WorkspaceEdit's documentChanges is supported

- .travis.yml
Node.js 7 reached end-of-life in 2017-06-30 and has been superceded by Node.js 8 which is an LTS release. Node.js 8 is included in the CI build so there is no reason to build Node.js 7 anymore. Node.js 9 is being built so the "latest and greatest" case is covered.
> Drop Node.js 7 from the CI build

- example/package-lock.json
- example/src/client.ts
- package-lock.json
- package.json
- src/commands.ts
- src/converter.ts
- src/languages.ts
- src/typings/monaco/index.d.ts
- src/workspace.ts
There are a couple of API changes from 0.10.x to 0.11.x.
1. The new `lightbulb` was added for Microsoft/monaco-editor#574 and fixes #11.
2. The commands and code action changes were made to support `textDocument/codeAction` and `workspace/executeCommand` due to the changes from https://github.com/Microsoft/vscode/commit/d86955c7e8c332f79bd99aa1313bfff11d52f895.
3. Monaco API changes caused some refactoring in the code for supporting `textDocument/hover` and `workspace/applyEdit`.
4. I ran into some problems with union types and promises that forced me to change the signature of some of the conversion code for `CompletionItem[]` and `CompletionList`. I documented my problem in [Microsoft/TypeScript#7294](https://github.com/Microsoft/TypeScript/issues/7294#issuecomment-373303058).
> Upgrade to Monaco 0.11.x

- .travis.yml
- README.md
- examples/browser/package-lock.json
- examples/browser/package.json
- examples/browser/src/client.ts
- examples/browser/src/index.html
- examples/browser/src/main.ts
- examples/browser/tsconfig.json
- examples/browser/webpack.config.js
- src/converter.ts
I've added a new `/examples/browser/` example that only uses the Monaco converters to get the JSON language service working with a Monaco Editor. This new example does not rely on Express to serve any content via Node.js. You simply build the example with `npm install` and `npm run build` and then open up `/examples/browser/lib/index.html` with a browser and the Monaco Editor should be up and running with JSON support.
The original example has been moved from `/example/` to `/examples/nodejs/`. I have also updated the README.md file to mention the new example.
> Create a browser example that only relies on HTML and JavaScript

- CHANGELOG.md
- src/converter.ts
It seems that `monaco.MarkerSeverity.Hint` is not being considered when converting a Monaco marker to an LSP Diagnostic so I fixed the converter.
https://github.com/TypeFox/monaco-languageclient/blob/3c7a4eb45df71d0461982ebc7a155e65d0c89129/src/converter.ts#L181-L191
> Convert all values of MarkerSeverity in the converter

- package.json
pulling of required version should be forced, otherwise lockfiles of npm/yarn may prevent an update of `vscode-languageserver-types`.
Signed-off-by: Alex Tugarev <alex.tugarev@typefox.io>
> add explicit dependency to `vscode-languageserver-types`

- package-lock.json
- package.json
this pulls a required fix from https://github.com/TypeFox/vscode-languageserver-node/pull/2.
> update base languageclient

- src/languages.ts
at least with latest monaco 0.12.0 the resolution of suggestion items is broken in some cases. it can be reproduced with JDT LS, when you continue typing a prefix of a suggestion shown after the suggestions were triggered explicitly. it happens that the `completion/resolve` params are [missing a `data` field](https://github.com/eclipse/eclipse.jdt.ls/issues/629#issuecomment-381702198).
the actual issue is, that monaco looses information, because the `CompletionItemProvider` won't fill up the given item, but returns a [new one, which is the converted result from LS](https://github.com/TypeFox/monaco-languageclient/compare/at/resolve-should-update-item?expand=1#diff-afa77f4a54ecc110291b19f59e543df7L96). 
monaco's `SuggestAdapter`, which calls the completion item provider, will just [update …
> Return updated items in `resolve*` operations

- .npmignore
- .travis.yml
- example/package-lock.json
- example/package.json
- example/src/client.ts
- example/src/json-server.ts
- example/webpack.config.js
- examples/browser/package-lock.json
- examples/browser/package.json
- examples/browser/src/client.ts
- package-lock.json
- package.json
- src/connection.ts
- src/console-window.ts
- src/disposable.ts
- src/monaco-commands.ts
- src/monaco-converter.ts
- src/monaco-diagnostic-collection.ts
- src/monaco-language-client.ts
- src/monaco-languages.ts
- src/monaco-services.ts
- src/monaco-workspace.ts
- src/register-vscode.ts
- src/services.ts
- src/vscode-api.ts
- src/vscode-compatibility.ts
- tsconfig.json
vscode compatiblity layer is introduced to make use of vscode-languageclient directly instead of vscode-base-languageclient
> upgrade to latest LSP

- src/monaco-languages.ts
Previously, providers were registered for every registered language, not just for the ones matching the documentSelector array passed to the LanguageClient config.
With this fix, language-specific providers are only registered for an existing language if there is a chance of matching, i.e.:
1. the language appears in the documentSelectors list
2. there is at least one documentSelector with non-language matching criteria
This reduces the risk of a conflict with existing providers, e.g. when using monaco-languages or monaco-json.
> fix: register providers only for languages matching the documentSelector

- src/monaco-converter.ts
While the LSP allows a `SignatureHelp`'s signatures array to be optional, Monaco does not so we should ensure that it Monaco's representation of a `SignatureHelp` is properly initialized with a zero length array if the value from the language server is `null` or `undefined`.
See Microsoft/monaco-editor#1045.
> Ensure that SignatureHelp and SignatureHelp has non-null arrays

- CHANGELOG.md
- examples/browser/src/client.ts
- package.json
- src/monaco-converter.ts
- src/monaco-languages.ts
With adaptation for the changes in the symbol API
> Bumping to monaco 0.14.2

- example/package-lock.json
- example/package.json
- example/tsconfig.json
- examples/browser/package-lock.json
- package-lock.json
- package.json
> fix #117: monaco-editor-core as a dev dependency

- example/package.json
- yarn.lock
`textDocument/documentLink` requests no longer work in the example because the Monaco bridge code uses 0.17.x APIs but the example still depends on 0.15.5.
> Update Monaco dependency in the example

- example/src/client.ts
Fixed the usage of the ReconnectingWebsocket in the client.ts of the example.
Was `undefined` but should be `[]` according to the documentation: https://www.npmjs.com/package/reconnecting-websocket
This was causing websocket handshake errors for Firefox and IE.
> Fix usage ReconnectingWebSocket example client.ts

- client/src/services.ts
We frequently override services, and often see the `'Language Client services has been overridden'` error message, even though it is working how we expect. 
By having `install` return a `Disposable`, it allows us to dispose of our old services first, before setting up new ones - avoiding the console error.
Other methods considered:
* `Uninstall` method
* Removing console error
* Adding parameter to `install` method to silence the console.error
Let me know if you'd prefer a different method than the current choice.
> Make Services.install be disposable

- client/src/monaco-converter.ts
fix #173: Monaco has more kinds in 0.17.0 breaking a logic of adjusting position by one. This PR maps kinds directly, later, for new versions, we will need to review a mapping.
Published under `dev` tag for testing in downstream projects.
> align CompletionItemKind with Monaco 0.17.0

- examples/browser/src/client.ts
> browser example: fix typo

- client/src/services.ts
If it's an error, it should throw, not just log. If it's a warning, it should log a warning. WDYT?
> Log a warning instead of an error when overriding the services

- client/src/vscode-api.ts
It seems that vscode-languageclient now requires the `EventEmitter` from the `vscode` api (https://github.com/microsoft/vscode-languageserver-node/blob/ee617c1f0c64a9d4ef7c6dcbb37189c7ae63ecd6/client/src/common/semanticTokens.ts#L126)
> Fix vscode api

- client/src/monaco-converter.ts
- client/src/monaco-language-client.ts
When upgrading to LSP 3.16.0 (and even some for LSP 3.15.0), some protocol conversion were not updated or added.
> Add missing protocol convertion

- example/package.json
- example/src/client.ts
In reference to the issue I reported in #254 
Note: the example was working perfectly fine, but for my custom fork, I was running into issues with `unknown parameter value byName`. This change helped rectify it for me and in theory should make the example solution more robust.
> Remove dependency of vscode-jsonrpc in example #254

- client/src/monaco-languages.ts
- client/src/services.ts
- client/src/vscode-api.ts
- example/package.json
- example/src/client.ts
- example/webpack.config.js
- examples/browser/package.json
- examples/browser/src/client.ts
In last version of the lsp specification, the `edit` field in a CodeAction is not mandatory anymore.
In such case, the client is supposed to call the server to resolve it when it needs to.
Unfortunately, the monaco api doesn't provide the way to do it properly.
As soon as https://github.com/microsoft/monaco-editor/issues/2663 is resolved, it will need to be properly implemented, this is a temporary "hack"
> Resolve code actions

- client/src/monaco-converter.ts
When converting diagnostics from the language client DIagnostic from into IMarkerData, the `tag` field was dropped.
This keeps that field present in the diagnostic.
Here's confirmation of this locally with the `Unnecessary` tag on all `false` values, and no diagnostics on `true`:
> Fix dropped tags in Diagnostic -> IMarkerData

- .editorconfig
- .vscode/extensions.json
- .vscode/settings.json
- CHANGELOG.md
- CONTRIBUTING.md
- License.txt
- client/package.json
- example/package.json
- example/src/client.ts
- example/webpack.config.js
- examples/browser/package.json
- examples/browser/src/client.ts
- package.json
- yarn.lock
@CGNonofr along with updates to the CHANGELOG I did the following:
- Updated CHANGELOG with entries for 0.14.0 to 0.17.3
- Updated Current Maintainers list in CONTRIBUTING and introduced a "Past Maintainers" section
- Make build work cross-platform with shx
- Updated vscode settings
- Added .editorconfig and added editorconfig plugin recommendation
- Use monaco-languageclient again in examples
> Update CHANGELOG from 0.14.0 to 0.17.3

- client/src/monaco-languages.ts
(Proper types will come with new monaco-editor release => see https://github.com/microsoft/monaco-editor/issues/2985)
Some languages servers can handle multiples languages (for instance `c` and `c++`) so the document selector contains 2 items.
The current code just [uses the selector language and fallback to '*'](https://github.com/TypeFox/monaco-languageclient/blob/3e8d949a13fe266ea4fd12300345067e58b2bb20/client/src/monaco-languages.ts#L68)
There is then 2 issues:
- If the document selector doesn't contain a language, we need to [check the selector at every provider call](https://github.com/TypeFox/monaco-languageclient/blob/3e8d949a13fe266ea4fd12300345067e58b2bb20/client/src/monaco-languages.ts#L78) (it works but it's not ideal)
- More than 1 provider will be registered for a single …
> Registrer providers using the document selector directly

- package-lock.json
- package.json
- packages/client/package.json
- packages/client/src/connection.ts
- packages/client/src/monaco-converter.ts
- packages/client/src/monaco-language-client.ts
- packages/client/src/monaco-languages.ts
- packages/client/src/services.ts
- packages/client/src/vscode-api.ts
- packages/examples/browser/package.json
- packages/examples/client/package.json
- packages/examples/client/src/client.ts
- packages/examples/node/package.json
- packages/examples/node/src/json-server-launcher.ts
Notes:
- InlineValue feature is not yet supported by monaco, and it's not possible to NOT register the feature
> Update the protocol to version 3.17

- packages/client/src/monaco-converter.ts
- packages/client/src/monaco-languages.ts
- packages/client/src/services.ts
- packages/client/src/vscode-api.ts
Fix for https://github.com/TypeFox/monaco-languageclient/issues/351
also fix for https://github.com/TypeFox/monaco-languageclient/issues/293
> Fix code action diagnostics

- packages/client/src/connection.ts
- packages/client/src/converters.ts
- packages/client/src/monaco-language-client.ts
- packages/client/src/services.ts
Including such code can break things by using the nodejs api like `process`
> Do not include node code

- packages/client/src/monaco-language-client.ts
Some features are not supported at all:
- WorkspaceSymbolFeature
- TypeHierarchyFeature
- CallHierarchyFeature
- DidCreateFilesFeature, DidDeleteFilesFeature, DidRenameFilesFeature, WillCreateFilesFeature, WillDeleteFilesFeature, WillRenameFilesFeature
- InlineValueFeature (for the moment)
- NotebookDocumentSyncFeature
- FileSystemWatcherFeature
Some require some code and are not `builtin`:
- WillSaveFeature, WillSaveWaitUntilFeature, DidSaveTextDocumentFeature
- ConfigurationFeature, SyncConfigurationFeature
- ProgressFeature
> Remove unsupported features

- package-lock.json
- package.json
Shouldn't we generally stick to node LTS? npm `7.10.0` is the npm version bundled with node `16.0.0` that's why I choose that version number.
> Introduce global engines entries for node and npm

- packages/client/src/monaco-language-client.ts
For some reasons, if the server sends a capability registration batch to the client and one feature is not registered on the client, all registration after it in the list won't be registered (see https://github.com/microsoft/vscode-languageserver-node/blob/a6f0d22d2c6842337ad135c13d2f945e53b1a6e4/client/src/common/client.ts#L1741)
Do you have a better idea?
> Clean unregistered featured from registration requests

- CHANGELOG.md
- README.md
- index.html
- package-lock.json
- package.json
- packages/examples/browser-lsp/index.html
- packages/examples/browser-lsp/package.json
- packages/examples/browser-lsp/src/client.ts
- packages/examples/browser-lsp/src/serverWorker.ts
- packages/examples/browser-lsp/tsconfig.json
- packages/examples/browser-lsp/vite.config.worker.ts
This resolves #368 and implements client and server in the browser. Server runs in a worker and they use `vscode-languageserver-protocol/browser` for communication.
> Add example with client and server both running in the browser

- .eslintrc.js
- .vscode/launch.json
- README.md
- package-lock.json
- package.json
- packages/client/CHANGELOG.md
- packages/client/package.json
- packages/client/src/index.ts
- packages/client/tsconfig.cjs.json
- packages/client/tsconfig.json
- packages/examples/browser-lsp/tsconfig.json
- packages/examples/browser-old/tsconfig.json
- packages/examples/browser/tsconfig.json
- packages/examples/client/tsconfig.json
- packages/examples/node/package.json
- packages/examples/node/src/json-server-launcher.ts
- packages/examples/node/src/server.ts
- packages/examples/node/tsconfig.json
- packages/vscode-ws-jsonrpc/CHANGELOG.md
- packages/vscode-ws-jsonrpc/package.json
- packages/vscode-ws-jsonrpc/tsconfig.cjs.json
- packages/vscode-ws-jsonrpc/tsconfig.json
- tsconfig.json
- vite.config.ts
Added `typesVersions` to monaco-languageclient and vscode-ws-jsonrpc, so exports can be properly imported with TS:
I did not understand why the "exports" lead to import problems in typescript (node example) until I found this:
https://github.com/teppeis/typescript-subpath-exports-workaround
`vscode-ws-jsonrpc` gets a 1.0.1 release once this is merged.
and it makes sense to release a 2.0.2 of `monaco-languageclient`, because of the  `typesVersions`. Do you have other things that should be fixed as well?
> Align all tsconfigs and vscode-ws-jsonrpc provides esm/cjs

- package-lock.json
- packages/client/package.json
- packages/client/src/disposable.ts
- packages/examples/browser-lsp/src/client.ts
- packages/examples/browser-old/src/client.ts
- packages/examples/browser/src/client.ts
- packages/examples/client/src/client.ts
- packages/examples/node/src/json-server-launcher.ts
It may look like a downgrade, but don't get fooled!
At first, I was trying to implement the latest available vscode api, but it was a mistake.
I'm now implementing the vscode api corresponding to the last released monaco version (which is quite old, > 3 months) so the 1.67 (instead of the 1.68)
It will be a little weird that the last published version is not the hightest number until a new monaco editor version will be released and I will be able to release a v1.69 of monaco-vscode-api.
The new version of monaco-vscode-api is using more code from vscode itself, and less copy/pastes, which I assumed will be more robust. It also implements some endpoints that weren't implemented yet.
It also exports 2 new modules: `service-override/messages` and `service-override/modelEditor` which allow to …
> Update vscode api

- packages/examples/react-client/src/app.tsx
**Issue**
When I implemented the current react-client example on a long-running server instance, I saw exploding memory usage but no CPU usage. The memory hung for a long time but was never released. I checked my console network tab, and the connections were never being closed.  
**This pull request**
I believe there need to be calls made to close the web sockets, or else there will be a build up of memory on the server.
I added calls to close the web socket on component unmount and page exit/reload
> Close websocket

- packages/vscode-ws-jsonrpc/src/socket/reader.ts
This PR improves handling of parse errors for incoming message.
> Gracefully handle JSON.parse errors

- README.md
- package-lock.json
- packages/client/CHANGELOG.md
- packages/client/package.json
- packages/client/src/monaco-language-client.ts
- packages/client/src/monaco-vscode-api-services.ts
- packages/examples/main/package.json
- packages/examples/main/src/browser/main.ts
- packages/examples/main/src/client/main.ts
- packages/examples/main/src/common.ts
- packages/examples/main/src/langium/main.ts
- packages/examples/main/src/react/app.tsx
- packages/verify/pnpm/package.json
- packages/verify/vite/package.json
- packages/verify/vite/src/client/main.ts
- packages/verify/webpack/package.json
- packages/verify/webpack/src/client/main.ts
- packages/verify/yarn/package.json
- packages/vscode-ws-jsonrpc/package.json
- vite.config.ts
@CGNonofr I have a problem even if I only include files and model. Any idea on this?
I changed `initServices` that users can only include editor or views as you outlined in the monaco-vscode-api README
> Adapt to monaco-vscode-api-1.79.1

- README.md
- package-lock.json
- package.json
- packages/client/CHANGELOG.md
- packages/client/package.json
- packages/client/src/monaco-vscode-api-services.ts
- packages/examples/CHANGELOG.md
- packages/examples/package.json
- packages/examples/src/common/client-commons.ts
- packages/examples/src/langium/statemachineClient.ts
- packages/examples/src/python/client/main.ts
- packages/verify/pnpm/package.json
- packages/verify/vite/package.json
- packages/verify/webpack/package.json
- packages/verify/yarn/package.json
Looking good apart from this:
It is called from inside `monaco.js`:
> Updated to monaco-vscode-api@1.83.10. Align with changes

- README.md
- package-lock.json
- package.json
- packages/client/CHANGELOG.md
- packages/client/package.json
- packages/examples/CHANGELOG.md
- packages/examples/package.json
- packages/examples/src/common/client-commons.ts
- packages/verify/pnpm/package.json
- packages/verify/vite/package.json
- packages/verify/webpack/package.json
- packages/verify/yarn/package.json
@CGNonofr there are suddenly problems:
This is an error with unchanged code in the JSON client example
This one seems to come from `WorkbenchContextKeysHandler`:  
I see initialization errors with `IExtensionService` in the Statemachine Example as well.
> Update to monaco-vscode-api@1.85.0 and monaco-editor@0.45.0

- packages/vscode-ws-jsonrpc/src/socket/reader.ts
Implementing `dispose()` according to the spec:
https://github.com/microsoft/vscode-languageserver-node/blob/21f4f0af6bf1623483c3e65f36e550bfdb6245a6/jsonrpc/src/common/messageReader.ts#L48
Although the `listen()` method returns a disposable callback, it seems like it's not used. Instead, the `dispose()` method is called on the reader (see [here](https://github.com/microsoft/vscode-languageserver-node/blob/21f4f0af6bf1623483c3e65f36e550bfdb6245a6/jsonrpc/src/common/connection.ts#L1553)).
Without implementing the dispose method, you can stop the language client, but calling `languageClient.start()` will not restart it properly.
> Implement dispose method on WebSocketMessageReader.

- packages/examples/src/browser/main.ts
- packages/examples/src/common/example-apps-common.ts
- packages/examples/src/groovy/client/main.ts
- packages/examples/src/json/client/wrapperWs.ts
- packages/examples/src/langium/langium-dsl/config/classicConfig.ts
- packages/examples/src/langium/langium-dsl/config/extendedConfig.ts
- packages/examples/src/langium/statemachine/config/wrapperStatemachineConfig.ts
- packages/examples/src/langium/statemachine/main-react.tsx
- packages/examples/src/langium/statemachine/main.ts
- packages/examples/src/python/client/config.ts
- packages/examples/src/ts/wrapperAdvanced.ts
- packages/examples/src/ts/wrapperTs.ts
- packages/examples/wrapper_ts.html
- packages/wrapper-react/src/index.tsx
- packages/wrapper/src/commonTypes.ts
- packages/wrapper/src/editorAppBase.ts
- packages/wrapper/src/editorAppClassic.ts
- packages/wrapper/src/editorAppExtended.ts
- packages/wrapper/src/index.ts
- packages/wrapper/src/languageClientWrapper.ts
- packages/wrapper/src/userConfig.ts
- packages/wrapper/src/utils.ts
- packages/wrapper/src/wrapper.ts
- packages/wrapper/test/editorAppBase.test.ts
- packages/wrapper/test/editorAppClassic.test.ts
- packages/wrapper/test/editorAppExtended.test.ts
- packages/wrapper/test/helper.ts
- packages/wrapper/test/languageClientWrapper.test.ts
- packages/wrapper/test/wrapper.test.ts
- vite.config.ts
Re-work how to configure code in `UserConfig` and make `languageId` no longer required and do not enforce it in the editor model.
This is now uri or file extension driven. `languageId` can be optionally enforced (WA for classical editor in the wrapper).
It is now possible to create an editor without any text or model and update the model or `codeResources` later. This is demonstrated here: https://github.com/TypeFox/monaco-languageclient/blob/issue-639/packages/examples/src/langium/statemachine/main.ts#L28-L42
Fixes #639
> Update code configuration. languageId is no longer required.

- packages/wrapper/src/editorAppExtended.ts
- packages/wrapper/test/wrapper.test.ts
Fixes #679 
There was a bug where disposing and then reinitializing an `EditorAppExtended` where an extension has `filesOrContents` would result in an exception being thrown due to not disposing these files from the last time the extension was registered. This fixes that by disposing of the results of `registerFileUrl` in the `disposeApp` method.
I added a test to exercise this; the test introduced in the first commit exhibits the `Error: file 'extension-file://undefined.undefined/' already exists` error, and that error goes away in the second commit. Unfortunately, when I run this test suite, I also get a bunch of "Array buffer allocation failed" errors that seem to come from somewhere in VSCode's services. I tried using the `updateExtendedAppPrototyp` test helper to fix this, but that …
> Dispose extension files in EditorAppExtended

- packages/wrapper-react/src/index.tsx
- packages/wrapper-react/test/index.test.tsx
Fixes #683 
Updates `MonacoEditorReactComp` to correctly handle changes to the `onTextChanged` prop.
Note: since there isn't a test suite for the React component on `main`, this branch includes changes from both this PR and https://github.com/TypeFox/monaco-languageclient/issues/681 . See [here](https://github.com/vrama628/monaco-languageclient/compare/react-component-did-update...vrama628:monaco-languageclient:react-on-text-changed) for a diff of just the changes relevant to this PR.
The first commit adds a test case that reproduces the issue, and the second commit fixes it. When I run the test after the fix, Vite seems to get stuck and infinitely hang; I wasn't able to figure out why. I'm open to suggestions on how to fix the test case to run properly in `vitest`, or I can just remove …
> Update onTextChanged in MonacoEditorReactComp

- packages/wrapper/src/editorAppBase.ts
- packages/wrapper/test/wrapper.test.ts
Fixes a bug that caused both diff editors to display the same model.
We ran into a bug with the diff editor where both the modified editor and original editor displayed the same content. When we inspected the editors in the browser, we found that they had the same `data-uri` value.
After tracing through the `editorAppBase.ts` file, we saw that the `getEditorUri` function accepts a boolean to determine whether to append 'Original'. But the `buildModelRef` function always passed `false` when building the model reference for both editors.
This pull request fixes the bug by passing a boolean parameter from `buildModelRef` to `getEditorUri` and ensuring that the URIs are different for both editors.
Here is a screenshot before the change, showing how the modified editor and original editor …
> Fix Diff Editor Model Refs

- packages/wrapper/test/wrapper.test.ts
This is a test case for https://github.com/TypeFox/monaco-languageclient/pull/680; we don't yet know how to get this test to work properly without unrelated errors happening, so I've [moved it to a separate draft PR as requested](https://github.com/TypeFox/monaco-languageclient/pull/680#issuecomment-2186726331).
> Test "Dispose extension files in EditorAppExtended"

- packages/client/src/vscode/services.ts
- packages/wrapper/src/vscode/services.ts
Currently, the `configureServices` function creates a default workspace config, but it is not passed to the `initialize` function. This PR passes the configuration to the `initialize` function. Moreover, to work properly, the `workspaceUri` must have the extension `.code-workspace`.
I previously reported a related issue here: https://github.com/CodinGame/monaco-vscode-api/issues/470
> Open default workspace

- package-lock.json
- package.json
- packages/wrapper-react/src/index.tsx
- packages/wrapper/src/wrapper.ts
This fixes #719 
`isRestarting` is no longer checked during destroy and only checked at  the beginning of `handleReInit`
> isRestarting is only checked and awaited at the beginning of handleReInit

- packages/examples/react_python.html
- packages/examples/react_statemachine.html
- packages/examples/src/langium/statemachine/main-react.tsx
- packages/examples/src/python/client/reactPython.tsx
- packages/wrapper-react/src/index.tsx
- packages/wrapper-react/test/index.test.tsx
- packages/wrapper/src/editorAppBase.ts
- packages/wrapper/src/index.ts
- packages/wrapper/src/utils.ts
- packages/wrapper/src/wrapper.ts
- packages/wrapper/test/wrapper.test.ts
- vitest.workspace.ts
As the title states, the react component became a function component to respect modern react patterns.
> Turned react component from class to function

- package-lock.json
- packages/examples/clangd.html
- packages/examples/ghp_clangd.html
- packages/examples/package.json
- packages/examples/resources/clangd/build-docker.sh
- packages/examples/resources/clangd/workspace/.clangd
- packages/examples/src/clangd/client/main.ts
- packages/examples/src/clangd/client/workerHandler.ts
- packages/examples/src/clangd/definitions.ts
- packages/examples/src/clangd/worker/clangd-server.ts
This is the result of a collaboration between @montymxb and me.
The application behaves similar as before, but then worker now uses IndexedDB as file system. You can also re-configure the client to load a complex workspace from a zip file.
The worker logic has been logically restructured to and the async file system handling and clangd init is now working smoothly.
> Clangd example improvements: IndexedDB usage and possibility to load workspace from zip file

- packages/examples/src/browser/main.ts
- packages/examples/src/eclipse.jdt.ls/client/main.ts
- packages/examples/src/groovy/client/main.ts
- packages/examples/src/json/client/wrapperWs.ts
- packages/examples/src/langium/langium-dsl/config/classicConfig.ts
- packages/examples/src/langium/langium-dsl/config/extendedConfig.ts
- packages/examples/src/langium/statemachine/config/wrapperStatemachineConfig.ts
- packages/examples/src/langium/statemachine/main.ts
- packages/examples/src/multi/twoLanguageClients.ts
- packages/examples/src/python/client/config.ts
- packages/examples/src/python/client/reactPython.tsx
- packages/examples/src/ts/wrapperTs.ts
- packages/wrapper-react/src/index.tsx
- packages/wrapper-react/test/index.test.tsx
- packages/wrapper/src/editorApp.ts
- packages/wrapper/src/wrapper.ts
- packages/wrapper/test/editorApp.test.ts
- packages/wrapper/test/helper.ts
- packages/wrapper/test/wrapper.test.ts
Text model content was not updated properly when updating code resources
Added additional unit tests
Variable naming alignment. Terminology is always modified and original derived from DiffEditor.
> Bugfix: Wrapper; Text model content is not properly updated with updateCodeResource

- packages/wrapper-react/src/index.tsx
Having the subscriptions stored in state will make it impossible to clean them as the `disposeOnTextChanged` callback will always access the old array without `onTextChangedSubscriptions` being in dep array
> clean subscriptions in react

- packages/examples/src/appPlayground/reactMain.tsx
- packages/examples/src/python/client/reactPython.tsx
- packages/wrapper-react/src/index.tsx
- packages/wrapper-react/test/index.test.tsx
- packages/wrapper/src/editorApp.ts
- packages/wrapper/src/wrapper.ts
- packages/wrapper/test/wrapper.test.ts
This was a bad design choice that is corrected. The react component should be thinnest possible layer around the wrapper.
> Move text changes handling from react component to the wrapper

- package-lock.json
- packages/client/src/commonTypes.ts
- packages/client/src/vscode/services.ts
- packages/client/test/fs/endpoints/emptyEndpoint.test.ts
- packages/client/test/vscode/services.test.ts
- packages/examples/src/appPlayground/config.ts
- packages/examples/src/bare/client.ts
- packages/examples/src/clangd/client/config.ts
- packages/examples/src/langium/langium-dsl/config/classicConfig.ts
- packages/examples/src/python/client/config.ts
- packages/wrapper-react/src/index.tsx
- packages/wrapper-react/test/helper.ts
- packages/wrapper-react/test/index.test.tsx
- packages/wrapper/package.json
- packages/wrapper/src/languageClientWrapper.ts
- packages/wrapper/src/vscode/services.ts
- packages/wrapper/src/wrapper.ts
- packages/wrapper/test/helper.ts
- packages/wrapper/test/languageClientWrapper.test.ts
- packages/wrapper/test/worker/langium-server.ts
- packages/wrapper/test/wrapper.test.ts
- vitest.config.ts
I moved some tests around (wrong places) as well.
Fixing the wrapper handling in case of error introduced required changes to the react component and to several tests.
After thinking about #855
> Handle languageclient errors cases more robustly

- packages/wrapper-react/src/index.tsx
- Replaced multiple `useEffect` and `useCallback` hooks with a single, cohesive `useEffect`.
- Improved container reference management and initialization.
- Streamlined error handling and disposal processes for better reliability.
These adjustments are intended to reduce code complexity, making the lifecycle management of the Monaco editor component more straightforward and maintainable.
Please review these changes and provide any feedback. Thank you!
> refactor: replace all `useEffect` and `useCallback` with one `useEffect`

- packages/wrapper-react/README.md
- packages/wrapper/README.md
Updates the example usage in the wrapper README:
- `modified` instead of `main`
- `python` instead of `TypeScript`
- `extended` instead of `classic`
> Fix configuration wrapper readme

- packages/wrapper-react/src/index.tsx
Added a call to `destroyMonaco()` before initializing a new instance with `initMonaco()` and `await` it.
Added `if (wrapperRef.current.isStopping() === false)` to make sure the editor is not stopping to prevent double editors in react strict mode because in strict mode react will execute `useEffect` hooks twice
This ensures that the previous instance is completely disposed of before starting a new one, improving performance and stability.
Removed the cleanup function from the main `useEffect` because it runs each time the wrapper config changes
Added a new `useEffect` with an empty dependencies array and a cleanup function to make sure that the Monaco instance is disposed before the component unmounts
> fix: old monaco editor instance is not destroyed before a new one init

- packages/wrapper-react/README.md
- packages/wrapper/README.md
Related to #913 , adds associated usage & import to setup the monacoWorkerFactory w/ the default work factory.
> Update monaco-editor-react README for WorkFactory Usage

- packages/wrapper/src/editorApp.ts
- packages/wrapper/test/editorApp.test.ts
Fixes `DOMException: String contains an invalid character` in `verifyUrlOrCreateDataUrl` when a data url is created of a string that contains a Unicode character larger than one byte.
See https://developer.mozilla.org/en-US/docs/Web/API/Window/btoa#unicode_strings for a detailed explanation.
I had a special Unicode character in my language configuration which caused this error. Looks like the receiving side can deal with the UTF8 encoded string as it works as expected for me now.
> Fix data URL crash for Unicode characters

- docs/guides/configuration.md
- docs/guides/examples.md
- docs/guides/getting-started.md
- docs/guides/index.md
- docs/migration.md
- packages/client/README.md
- packages/client/src/vscode/apiWrapper.ts
- packages/client/src/vscode/config.ts
- packages/client/test/editorApp/editorApp-classic.test.ts
- packages/client/test/editorApp/editorApp.test.ts
- packages/client/test/editorApp/editorApp.wrongservices.test.ts
- packages/client/test/support/helper.ts
- packages/client/test/vscode/manager.test.ts
- packages/client/test/vscode/manager.wrongHtmlContainer.test.ts
- packages/client/test/worker/workerLoaders.test.ts
- packages/examples/src/appPlayground/config.ts
- packages/examples/src/appPlayground/reactMain.tsx
- packages/examples/src/browser/main.ts
- packages/examples/src/common/client/extendedClient.ts
- packages/examples/src/debugger/common/definitions.ts
- packages/examples/src/json/client/classic.ts
- packages/examples/src/langium/statemachine/config/statemachineConfig.ts
- packages/examples/src/langium/statemachine/main-react.tsx
- packages/examples/src/langium/statemachine/main.ts
- packages/examples/src/multi/twoLanguageClients.ts
- packages/examples/src/python/client/config.ts
- packages/wrapper-react/README.md
- packages/wrapper-react/test/index.test.tsx
- vitest.config.ts
I just wanted to improve the v9 to v10 migration guide.
Then I noticed that making `htmlContainer` mandatory is too limiting. It is no optional and only required with `ViewsService` and `WorkbenchService`. New units test are available to check the behaviour.
> Updated migration guide, relaxed requirement to specify htmlContainer

- packages/client/README.md
Hey there,
I updated to monaco-languageclient and noticed this error in the example.
Otherwise the migration went smooth, thanks a lot!
> fix example in client README
