TypeFox/monaco-languageclient

.gitignore
package.json
src/converter.ts
src/workspace.ts

Signed-off-by: Sven Efftinge <sven.efftinge@typefox.io>

spread the command arguments

---

src/workspace.ts

Allow overriding the rootUri in the workspace

---

src/services.ts

Signed-off-by: Christian Dietrich <christian.dietrich@itemis.de>

passing Options to createMonacoServices to allow a rootUri being set #31

---

README.md

Signed-off-by: Christian Dietrich <christian.dietrich@itemis.de>

fixed #28 (npm badges)

---

.travis.yml

Signed-off-by: Anton Kosiakov <anton.kosyakov@typefox.io>

[travis] building against node 8

---

License.txt
example/package-lock.json
example/package.json
example/src/index.html
example/src/json-server-launcher.ts
example/src/json-server.ts
example/src/main.ts
example/src/monaco-editor-core.d.ts
example/src/server.ts
example/tsconfig.json
example/webpack.config.js
package-lock.json
package.json
src/commands.ts
src/console-window.ts
src/converter.ts
src/diagnostic-collection.ts
src/disposable.ts
src/index.ts
src/services.ts
src/typings/glob-to-regexp/index.d.ts
src/typings/monaco/index.d.ts
src/workspace.ts
tsconfig.json

This PR updates dependencies in the lock file and fixes the follow-up issues. It fixes as well #64 and #39.

Upgrade dependencies

---

.github/CODEOWNERS
.gitpod.yml
.travis.yml
CONTRIBUTING.md
client/src/monaco-languages.ts
client/src/services.ts
package.json
scripts/init.sh

fix #154 - Since Monaco 0.17 can handle undefined values, converters are adjuster to propagate them directly to Monaco.

handle undefined values

---

.gitpod.yml
client/src/vscode-api.ts
scripts/auth.sh

rebased https://github.com/TypeFox/monaco-languageclient/pull/144

fix window.showMessage

---

client/package.json
package.json
yarn.lock

removed vscode dependency and replaced it with @types/vscode

---

client/src/monaco-converter.ts
example/src/json-server.ts

Implemented the conversion for `LocationLinks` in the  `asDefinitionResult` method.
This closes #190.
During the implementation I oriented myself to the implementation in the [VSCode client](https://github.com/microsoft/vscode-languageserver-node/blob/dd78cba181136e057cfcc4bb7bc17c7c78877648/client/src/protocolConverter.ts#L553)

Implemented support for "LocationLink" in the "onDefinition" method

---

README.md
package.json

I was unable to build & start as per documentation.

Update documentation for starting and building

---

README.md
index.html
package-lock.json
package.json
packages/client/package.json
packages/examples/browser/package.json
packages/examples/browser/src/client.ts
packages/examples/client/package.json
packages/examples/client/src/client.ts
packages/examples/client/tsconfig.json
packages/examples/client/webpack.config.js
packages/examples/client/webpack/index.html

Integrate webpack client example as second option

---

packages/client/package.json

feat(package.json): export monaco-converter

---

.github/workflows/actions.yml
README.md
package-lock.json
package.json
packages/client/package.json
packages/examples/browser-lsp/package.json
packages/examples/browser-lsp/vite.config.worker.ts
packages/examples/browser/package.json
packages/examples/client/package.json
packages/examples/server/package.json
packages/verify/vite/package.json
packages/verify/webpack/package.json
packages/vscode-ws-jsonrpc/package.json

- Added troubleshooting section to README (this closes #421 and #423)
- Update other dependencies as well
- Fixed GitHub Actions deprecation warnings
It's mostly dependency updates and please take a look at the Troubleshooting section (if it makes sense and is correct). Thanks

Update to monaco-editor 0.34.1

---

README.md
package-lock.json
packages/client/README.md
packages/examples/server/package.json
packages/examples/server/src/fs-utils.ts
packages/examples/server/src/json-server-launcher.ts
packages/examples/server/src/json-server.ts
packages/examples/server/src/server.ts
packages/vscode-ws-jsonrpc/README.md

This PR was triggered by #445 and corrects the example in the README.
I have polished the server example along and discovered something that we should discuss in another issue (#447).

Align vscode-ws-jsonrpc README and server example

---

README.md
package-lock.json
packages/client/CHANGELOG.md
packages/client/package.json
packages/client/src/monaco-vscode-api-services.ts
packages/examples/main/package.json
packages/examples/main/src/common.ts
packages/examples/main/src/langium/main.ts
packages/verify/vite/package.json
packages/verify/webpack/package.json

This is the main preparation for 6.1.0 release

Updating to monaco-vscode-api 1.79.0 and monao-editor 0.38.0

---

packages/examples/main/src/common.ts
packages/examples/main/src/python/client.ts
packages/examples/main/src/python/server.ts

- Added _searchParams_ parameter to the createUrl function
- Extended the python example to send in an authorization parameter
- Added verifyClient function for authorization & client tracking to the language server

Additional parameters for the URL creation

---

packages/examples/src/python/client/reactPython.tsx
packages/wrapper-react/src/index.tsx
packages/wrapper/src/wrapper.ts

This implements #612 . The usage is demonstrated in `reactPython` example.

react-comp passes the wrapper onLoad

---

package-lock.json
package.json
packages/examples/.gitignore
packages/examples/CHANGELOG.md
packages/examples/build/downloadResources.mts
packages/examples/package.json
packages/examples/src/langium/langium-dsl/config/extendedConfig.ts
packages/examples/tsconfig.build.json
tsconfig.build.json
vite.config.ts

This was the easiest way to integrate this. It closes #640

Added vsixPlugin and make extended editor in Langium use Github Theme

---

packages/examples/src/clangd/client/config.ts
packages/examples/src/eclipse.jdt.ls/client/main.ts
packages/examples/src/groovy/client/main.ts
packages/examples/src/json/client/wrapperWs.ts
packages/examples/src/langium/langium-dsl/config/classicConfig.ts
packages/examples/src/langium/langium-dsl/config/extendedConfig.ts
packages/examples/src/langium/statemachine/config/wrapperStatemachineConfig.ts
packages/examples/src/multi/twoLanguageClients.ts
packages/examples/src/python/client/config.ts
packages/wrapper/src/languageClientWrapper.ts
packages/wrapper/test/languageClientWrapper.test.ts

@RoddoWasHere and @CGNonofr what do you think about a joint type? Is this end-user friendly?
Fixes #779

Remove languageId configuration ambiguity

---

packages/wrapper/src/languageClientWrapper.ts

Fixed WebSocket type checking error

---

.vscode/launch.json
package-lock.json
package.json
packages/client/src/vscode/services.ts
packages/client/test/vscode/services.test.ts
packages/examples/package.json
packages/examples/src/appPlayground/main.ts
packages/examples/src/bare/client.ts
packages/wrapper/test/vscode/services.test.ts
vitest.config.ts

The theme flickering is prevented by this when using the wrapper as suggested by @CGNonofr [here](https://github.com/TypeFox/monaco-languageclient/issues/819#issuecomment-2573197462).

Ensure configuration is init before service init
